use ini::Ini;
use std::io::Write;
use std::str::FromStr;
use std::process::Command;
use filetime::FileTime;

const KERNEL_CONFIG: &str = "kernel/config.ini";
const GENERATED_LD: &str = "kernel/src/kernel.generated.ld";
const GENERATED_RS: &str = "kernel/src/config.generated.rs";

fn timestamp(f: &str) -> FileTime {
    let metadata = std::fs::metadata(f);
    match metadata {
        Ok(time) => FileTime::from_last_modification_time(&time),
        Err(_) => FileTime::zero()
    }
}

fn prepare_params() {
    let config = Ini::load_from_file(KERNEL_CONFIG)
        .expect("Can't find kernel config!");

    let mut f_ld = std::fs::File::create(GENERATED_LD)
        .expect("Can't create generated ld file!");
    writeln!(&mut f_ld, "/* Generated by xtask! Don't MODIFY IT! */")
        .unwrap();

    let mut f_rs = std::fs::File::create(GENERATED_RS)
        .expect("Can't create generated rs file!");
    writeln!(&mut f_rs, "/* Generated by xtask! Don't MODIFY IT! */")
        .unwrap();

    for (_, p) in (&config).iter() {
        for (k, v) in (&p).iter() {
            writeln!(&mut f_ld, "{} = {};", k, v).unwrap();

            let ret = if v.starts_with("0x") {
                usize::from_str_radix(v.trim_start_matches("0x"), 16)
            } else {
                usize::from_str(v)
            };

            let t = match ret {
                Ok(_) => "u64",
                _ => "&str",
            };

            writeln!(&mut f_rs, "const {}: {} = {};", k, t, v).unwrap();
        }
    }
}

fn clean_kernel() {
    let status = Command::new("cargo").arg("clean")
        .status().unwrap();

    if !status.success() {
        panic!("Err: {}", status.code().unwrap());
    }
}

fn build_kernel() {
    let status = Command::new("cargo").arg("build")
        .arg("--no-default-features")
        .args(["--package", "kernel"])
        .args(["--target", "kernel/src/arch/riscv64/riscv64.json"])
		.args(["-Z", "build-std=core,alloc"])
        .args(["-Z", "build-std-features=compiler-builtins-mem"])
        .arg("--release")
        .status().unwrap();

    if !status.success() {
        panic!("Err: {}", status.code().unwrap());
    }
}

fn to_binary() {
    let status = Command::new("riscv64-linux-gnu-objcopy")
        .args(["-O", "binary"])
        .arg("-S")
        .arg("target/riscv64/release/kernel")
        .arg("target/riscv64/release/kernel.bin")
        .status().unwrap();

    if !status.success() {
        panic!("Err: {}", status.code().unwrap());
    }
}

fn main() {
    /* Check config.ini updated? */
    if (timestamp(GENERATED_LD) < timestamp(KERNEL_CONFIG)) ||
        (timestamp(GENERATED_RS) < timestamp(KERNEL_CONFIG)) {

        /*
         * Prepare params for kernel:
         * Generate kernel.generated.ld and config.generated.rs
         * from config.ini.
         */
        prepare_params();

        /* Clean kernel */
        clean_kernel();
    }

    /* Build kernel */
    build_kernel();
    to_binary();
}
