/*
 * Use of this source code is governed by a MIT-style license
 * that can be found in the LICENSE file or
 * at https://opensource.org/licenses/MIT
 */

use std::fs::File;

fn main()
{
    let mut f = File::create("kernel_vars.generated.ld").unwrap();
    writeln!(f, "/* Generated by build.rs. DO NOT EDIT IT. */").unwrap();
    writeln!(f, "PROVIDE_HIDDEN(KERNEL_BASE = {:#x});", KERNEL_BASE).unwrap();
}
